import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Banner from '@/components/Banner'
import CodeMonkey from '@/components/CodeMonkey'
import DeveloperSearch from '@/components/DeveloperSearch'
import Army from '@/components/Army'
import RoyalCouncil from '@/components/RoyalCouncil'
import SelectionProcess from '@/components/SelectionProcess'
import HiringProblem from '@/components/HiringProblem'
import CodeStory from '@/components/CodeStory'
import BecomePart from '@/components/BecomePart'
import TheKing from '@/components/TheKing'
import Testimonial from '@/components/Testimonial'
import JoinOurCommunity from '@/components/JoinOurCommunity'
import PaymentPlans from '@/components/PaymentPlans'
import NinjaCode from '@/components/NinjaCode'
import FAQs from '@/components/FAQs'
import WeeklyProgress from '@/components/WeeklyProgress'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className='mt-10 '>
        <Navbar />
      </nav>
      <section className=' mt-8 relative'><Banner />
        <img src="banner-image.svg" alt="developer coding with a laptop keyboard" className='hidden lg:block absolute right-0
        bottom-0 h-[90%]'  />
      </section>

      <section className='mt-44  w-[70]'><CodeMonkey /></section>

      <section className='mt-44 '><DeveloperSearch /></section>

      <section>
        <section className='mt-44'><Army /></section>
        <div className='flex justify-between relative mt-40'>
          <div class="slide-right -rotate-12 ">
            <div className='flex justify-center items-center p-3'>
              <img src="/techs/AWS.svg" alt="" className='h-[120px]' />
              <img src="/techs/language1.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/language2.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/language3.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/language4.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/language5.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/language6.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/language7.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/language8.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/ROR.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/flutter.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/Android.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/tailwind.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/python.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/vue-js.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/css.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/Django.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/react-native.svg" alt="" className='h-[120px] mx-14' />
              <img src="/techs/language9.svg" alt="" className='h-[120px]' />
              </div>
          </div>
          <img src="castle-updated.svg" alt="Castle of multiple programming languages React Angular Ruby on Rails
        java javascript typescript c++ c# and manymore" className='w-[500px] absolute  bottom-2 right-[-10%]  ' />
        </div>
      </section>

      <section className='mt-44'><RoyalCouncil /></section>

      <section className='flames-bg mt-32'>
        <section className='mt-32'><SelectionProcess /></section>
      </section>

      <section className='mt-44'><HiringProblem /></section>

      <section className='mt-44'><CodeStory /></section>

      <section className='mt-32 '><BecomePart /></section>

      <section className='mt-44'><TheKing /></section>

      <section className='mt-44'><Testimonial /></section>

      <section className='mt-32 '><JoinOurCommunity /></section>

      <section className='mt-44'><WeeklyProgress /></section>

      <section className='mt-44'><PaymentPlans /></section>

      <section className='mt-44'><NinjaCode /></section>

      <section className='flames-bg mt-32'>
        <section className='mt-44'><FAQs /></section>
      </section>




    </>
  )
}
