import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Banner from '@/components/Banner'
import CodeMonkey from '@/components/CodeMonkey'
import DeveloperSearch from '@/components/DeveloperSearch'
import Army from '@/components/Army'
import RoyalCouncil from '@/components/RoyalCouncil'
import SelectionProcess from '@/components/SelectionProcess'
import HiringProblem from '@/components/HiringProblem'
import CodeStory from '@/components/CodeStory'
import BecomePart from '@/components/BecomePart'
import TheKing from '@/components/TheKing'
import Testimonial from '@/components/Testimonial'
import JoinOurCommunity from '@/components/JoinOurCommunity'
import PaymentPlans from '@/components/PaymentPlans'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className='mt-10 '>
        <Navbar />
      </nav>
      <section className=' mt-8 relative'><Banner />
        <img src="banner-image.svg" alt="developer coding with a laptop keyboard" className='hidden lg:block absolute right-0
        bottom-0 h-[90%]'  />
      </section>

      <section className='mt-40  w-[70]'><CodeMonkey /></section>

      <section className='mt-40 '><DeveloperSearch /></section>

      <section className='mt-32'><Army /></section>

      <section className='mt-32'><RoyalCouncil /></section>

      <section className='flames-bg mt-32'>
        <section className='mt-32'><SelectionProcess /></section>
      </section>

      <section className='mt-32'><HiringProblem /></section>

      <section className='mt-32'><CodeStory /></section>

      <section className='mt-32'><BecomePart /></section>

      <section className='mt-32'><TheKing /></section>

      <section className='mt-32'><Testimonial /></section>

      <section className='mt-32'><JoinOurCommunity /></section>

      <section className='mt-32'><PaymentPlans /></section>
    </>
  )
}
